### ISSUE TITLE
결제 승인 API 응답의 payMethod 신용카드, 가상계좌 수정 요청

### ISSUE THREAD

**Issue by ray-leemingyu** [nicepayments/nicepay-manual#7]
안녕하세요

결제 승인 API 응답의 payMethod 속성의 신용카드가 원래는 대문자 `CARD`로 되어있었는데요. 실제로는 소문자 `card`로 응답이 옵니다.
나이스페이 포 스타트업 상점 1:1 문의를 통해 검토 요청을 드렸더니 지난 주에 문서를 수정하는 작업을 하신 것 같아요.
https://github.com/nicepayments/nicepay-manual/commit/34aec460aa26bf0d05d236c9453e77d555c9f7f3#

근데 가상계좌는 사라지고 신용카드만 남고, 신용카드가 2개로 수정이 된 것 같습니다.

확인 부탁드립니다.

**Comment by SeokRae** [comment]
내용 확인하여 5/17 반영하도록 하겠습니다.
